%YAML:1.0

#-------------------------------------------
# Camera Parameters. Adjust as necessary.
#-------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 525.000000
Camera.fy: 525.000000
Camera.cx: 319.500000
Camera.cy: 239.500000

Camera.k1: 0.000000
Camera.k2: 0.000000
Camera.p1: 0.000000
Camera.p2: 0.000000
Camera.k3: 0.000000

Camera.width: 320
Camera.height: 240

# Camera frames per second
Camera.fps: 35.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far Threshold. Baseline times.
ThDepth: 200.0

# Depthmap values factor.
DepthMapFactor: 1.0

#-------------------------------------------
# ORB Parameters
#-------------------------------------------

# ORB Extractor: Number of features per image.
ORBextractor.nFeatures: 3000

# ORB Extractor: Scale factor between levels in the scale pyramid.
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid.
ORBextractor.nLevels: 8

# ORB Extractor: Fast Threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impoese iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast.
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 2

#-------------------------------------------
# Viewer Parameters
#----------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 1
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500
